catalogo/urls.py
from django.urls import path
from .views import CatalogoListView, CatalogoDetailView

urlpatterns = [
     path('', CatalogoListView.as_view(), name="catalogos"),
     path('<int:pk>/<slug:slug>', CatalogoDetailView.as_view(), name="catalogo"),
     # path('tipo-de-Inmueble/<int:tipo_id>/', tipo.as_view(), name="tipo"),
]

core/urls.py
from django.urls import path
from . import views
from .views import home, about, services
urlpatterns = [
     path('', home.as_view(), name="home"),
     path('historia/', about.as_view(), name="historia"),
     path('servicios/', services.as_view(), name="servicios"),
]

inmo/urls.py
from django.contrib import admin
from django.urls import path, include
from catalogo import views as catalogo_views

#CUSTOM ADMIN
from django.conf import settings
settings

urlpatterns = [
    path('', include('core.urls')),
    path('catalogos/', include('catalogo.urls')), 
    path('page/', include('pages.urls')),
    path('contacto/', include('contact.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


#Custom Title for admin
admin.site.site_header = "INMOBILIARIA ARRALLANES"
admin.site.index_title = "Panel de administrador"
admin.site.site_title = "INMOBILIARIA ARRALLANES"

catalogo/models.py
from django.db import models
from django.utils.timezone import now
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField 

# Create 1 models
class Characteristics(models.Model):
    name = models.CharField(max_length=150, verbose_name = "Nombre de la Característica")
    created = models.DateTimeField(auto_now_add=True, verbose_name = "Fecha de Creación")
    updated = models.DateTimeField(auto_now=True, verbose_name = "Fecha de Edición")

    class Meta:
        verbose_name = "Característica"
        verbose_name_plural = "Características"
        ordering = ["-created"]
    
    def __str__(self):
        return self.name

class Tipos_de_inmuebles(models.Model):
    name = models.CharField(max_length=150, verbose_name = "Tipo de Inmueble", default='Otros')
    created = models.DateTimeField(auto_now_add=True, verbose_name = "Fecha de Creación")
    updated = models.DateTimeField(auto_now=True, verbose_name = "Fecha de Edición")
   
    class Meta:
        verbose_name = "Tipo de Inmueble"
        verbose_name_plural = "Tipos de Inmuebles"
        ordering = ["-created"]
    
    def __str__(self):
        return self.name

# Create 2 models
class Catalogo(models.Model):
    TYPE_COUNTRY = (
        ('M' , 'México'),
        ('O' , 'Otro'),
    )
    highlight = models.BooleanField(default=False, verbose_name = "Propiedad Destacada")
    title = models.CharField(max_length=150, verbose_name = "Título")
    subtitle = models.CharField(max_length=150, verbose_name = "Subtítulo")
    description = RichTextField(verbose_name = "Descripción")
    published = models.DateTimeField(verbose_name="Fecha de publicación", default=now)
    author =  models.ForeignKey(User, verbose_name="Vendedor", on_delete=models.PROTECT, blank=True, null=True)
    characteristics = models.ManyToManyField(Characteristics, verbose_name="Características" )
    typeC  = models.ManyToManyField(Tipos_de_inmuebles, verbose_name = "Tipo de Inmueble", related_name="get_posts" )
    numcontrol =  models.IntegerField(unique=True, verbose_name = "Número de Control")
    Idcontrol = models.IntegerField(unique=True, verbose_name = "Código de Control")
    Rentprice =  models.IntegerField(blank=True, null=True, verbose_name = "Precio Renta")
    Sellprice = models.IntegerField(blank=True, null=True, verbose_name = "Precio Venta")
    googleS = models.URLField(blank=True, null=True, verbose_name = "Google Street View")
    
    country = models.CharField(max_length=1, choices=TYPE_COUNTRY, verbose_name = "País")
    state = models.CharField(max_length=150, verbose_name = "Estado")
    city = models.CharField(max_length=150, verbose_name = "Ciudad")
    street = models.CharField(max_length=200, verbose_name = "Calle")
    zipcode = models.IntegerField(verbose_name = "Código Postal")
    Numint = models.IntegerField(blank=True, null=True, verbose_name = "Número Interno")
    Numext = models.IntegerField(blank=True, null=True, verbose_name = "Número Externo")
    phone = models.IntegerField(verbose_name = "Número De Contacto")
    email = models.EmailField(verbose_name = "Email")

    titleHero = models.CharField(max_length=150, verbose_name = "Título | Hero Imagen", default='Título | Hero Imagen')
    imgHero = models.ImageField(verbose_name = "Imagen Principal", upload_to="catalogo")
    descriptionimgHero = RichTextField(verbose_name = "Descripción | Hero Imagen", default='Descripción | Hero Imagen')
    
    titleimgA = models.CharField(max_length=150, verbose_name = "Título | Primera Imagen", default='Título | Primera Imagen')
    imgA = models.ImageField(blank=True, null=True, verbose_name = "Carrusel Imagen I", upload_to="catalogo")
    descriptionimgA = RichTextField(verbose_name = "Descripción | Primera Imagen", default='Descripción | Primera Imagen')

    titleimgB = models.CharField(max_length=150, verbose_name = "Título | Segunda Imagen", default='Título | Segunda Imagen')
    imgB = models.ImageField(blank=True, null=True, verbose_name = "Carrusel Imagen II", upload_to="catalogo")
    descriptionimgB = RichTextField(verbose_name = "Descripción | Segunda Imagen", default='Descripción | Segunda Imagen')

    titleimgC = models.CharField(max_length=150, verbose_name = "Título | Tercera Imagen", default='Tercera | Hero Imagen')
    imgC = models.ImageField(blank=True, null=True, verbose_name = "Carrusel Imagen III", upload_to="catalogo")
    descriptionimgC = RichTextField(verbose_name = "Descripción | Tercera Imagen", default='Descripción | Tercera Imagen')

    titleimgD = models.CharField(max_length=150, verbose_name = "Título | Cuarta Imagen", default='Título | Cuarta Imagen')
    imgD = models.ImageField(blank=True, null=True, verbose_name = "Carrusel Imagen IV", upload_to="catalogo")
    descriptionimgD = RichTextField(verbose_name = "Descripción | Cuarta Imagen",  default='Descripción | Cuarta Imagen')
   
    prototype = models.ImageField(blank=True, null=True, verbose_name = "Render")
    created = models.DateTimeField(auto_now_add=True, verbose_name = "Fecha de Creación")
    updated = models.DateTimeField(auto_now=True, verbose_name = "Fecha de Edición")
  
    # """ Traductor """ 
    class Meta: 
        verbose_name = "Inmueble"
        verbose_name_plural = "Inmuebles"
        ordering = ["-created"]
    
    def __str__(self):
        return self.title

catalogo/views.py
from .models import Catalogo, Tipos_de_inmuebles

from django.views.generic.list import ListView
from django.views.generic.detail import DetailView

class CatalogoListView(ListView):
    model = Catalogo
   
class CatalogoDetailView(DetailView):
    model = Catalogo
    

catalogo/templates/catalogo/_catalogo.html
<div class="row p-4 sayblock">
{% for catalogo in catalogo_list|dictsort:"id" reversed %}

<div class="inmueble p-0">
  <div class="internal">
      <div class="verPos">
          <a href="{% url 'catalogo' catalogo.id catalogo.title|slugify %}" target="_blank">
              <i class="fas fa-search"></i>
          </a>    
      </div>
      <img src="{{catalogo.imgHero.url}}" class="Cimagen" alt="{{catalogo.title}}">
      <div class="price">
          <h3><i class="fas fa-dollar-sign"></i> {{catalogo.Sellprice}}</h3>
      </div> 
      <div class="info">
        <div class="cat">
            {% for catalogo in catalogo.typeC.all  %}
            <i class="fas fa-bookmark"></i> {{catalogo.name}}
            {% endfor %}
        </div>
          <h2>
          <a href="{% url 'catalogo' catalogo.id catalogo.title|slugify %}" target="_blank">
          {{catalogo.title|truncatechars:"23"}}
          </a>
          </h2>
        <p class="descriptionC">
            {{catalogo.description|striptags|safe|truncatechars:"140"}}
        </p>
       <div class="donde">
          <i class="fas fa-map-marker-alt fa-pull-left"></i>{{catalogo.state}}
       </div>
      </div>

  <div class="Card_footer">
      <ul class="list-inline d-flex justify-content-around">
          <li class="list-inline-item">
              <a href="{{catalogo.googleS}}" target="_blank">
                <i class="fas fa-street-view"></i>
              </a>
          </li>
          <li class="list-inline-item">
                <a href="#" target="_blank">
                    <i class="fas fa-file-pdf"></i>
                </a>
            </li>
          <li class="list-inline-item">
              <a href="tel:{{catalogo.phone}}" target="_blank">
                <i class="fas fa-phone"></i>
              </a>
          </li> 
          <li class="list-inline-item">
                <a href="mailto:{{catalogo.email}}" target="_blank">
                    <i class="fas fa-envelope"></i>
                </a>
            </li>
      </ul>
  </div>
  </div>
</div>
{% endfor %} 

</div>

catalogo/templates/catalogo/catalogo_detail.html
{% extends 'core/base.html' %} {% load static %} {% block title %}

{{ catalogo.title }}

{% endblock %} {% block content %}
<div class="container sayAboutdetail ">
  <div class="row">
    <div class="col-12">
      <section class="hero">
        <div class="container-fluid">
          <div class="row">
            <div class="col-6">
           
             <div id="carouselExampleFade" class="carousel slide carousel-fade ImgCaru" data-ride="carousel">
              <div class="carousel-inner">
                <div class="carousel-item active">
                  <img src="{{ catalogo.imgHero.url }}" class="d-block w-100" alt="{{catalogo.titleHero}}">
                </div>
                <div class="carousel-item">
                  <img src="{{ catalogo.imgA.url }}" class="d-block w-100" alt="{{catalogo.titleimgA}}">
                </div>
                <div class="carousel-item">
                  <img src="{{ catalogo.imgB.url }}" class="d-block w-100" alt="{{catalogo.titleimgB}}">
                </div>
                <div class="carousel-item">
                  <img src="{{ catalogo.imgC.url }}" class="d-block w-100" alt="{{catalogo.titleimgC}}">
                </div>
                <div class="carousel-item">
                  <img src="{{ catalogo.imgD.url }}" class="d-block w-100" alt="{{catalogo.titleimgD}}">
                </div>
              </div>
              <a class="carousel-control-prev" href="#carouselExampleFade" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
              </a>
              <a class="carousel-control-next" href="#carouselExampleFade" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
              </a>
            </div>
            </div>
            <div class="col-6">
             <div class="heroTex">
              <h1>{{ catalogo.title }}</h1>
              {% for catalogo in catalogo.typeC.all %}
              <i class="fas fa-bookmark"></i> {{ catalogo.name }}
              {% endfor %}
              <p class="mt-3">
                {{catalogo.description|striptags|safe|truncatechars:"140"}}
              </p>
             </div>
            </div>
          </div>
        </div>
      </section>
    </div>
  </div>
  <!--  -->
  <!--  -->
  <!--  -->
 
  <div class="barraflotante">
    <div class="precioFlotant">
          <h3>
            <i class="fas fa-dollar-sign"></i> {{ catalogo.Sellprice }}
          </h3>
    </div>
    <div class="telFlotante">
      <h3>
        <a href="tel:{{catalogo.phone}}">
            <i class="fas fa-phone"></i> {{catalogo.phone}}
        </a>
      </h3>
    </div>
    <div class="mailFlotante">
      <h3>
        <a href="mailto:{{catalogo.email}}">
            <i class="fas fa-envelope"></i> {{catalogo.email}}
        </a>
      </h3>
    </div>
   
  </div>
  <!--  -->
  <!--  -->
  <!--  -->
  <section
    class="sayDescription"
    style="background:url('{{ catalogo.imgHero.url }}')"
  >
    <div class="plesta p-5">
      <div class="container">
        <div class="row">
          <div class="col-10 offset-1 py-3">
            <p>{{ catalogo.description | safe }}</p>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!--  -->
  <!--  -->
  <!--  -->
  <section class="sayInterested">
    <div class="container">
      <div class="row">
        <div class="col">

        </div>
        <!--  -->
        <div class="col-sm-12 col-md-3">
          <form action="">

          </form>
        </div>
      </div>
    </div>
  </section>
  <!--  -->
  <!--  -->
  <!--  -->
</div>

{% endblock %}

catalogo/templates/catalogo/catalogo_list.html
{% extends 'core/base.html' %}
{% load static %}

 {% block title %} 
 
 Catálogos 
 
 {% endblock %} 


{% block content %}
<div class="container sayList">
  <div class="row">
    <div class="col-md-8">
        {% include 'catalogo/_catalogo.html' %}
    </div>
    <div class="col-sm-12 col-md-3">

    </div>
  </div>
</div>
{% endblock %}

catalogo/templates/catalogo/tipo.html
{% extends 'core/base.html' %}
{% load static %}

 {% block title %} 
 
 Tipo de inmueble 
 
 {% endblock %} 


{% block content %}

{% for catalogo in tipo.get_posts.all %}
<div class="inmueble">
  <div class="blockImagen" style="background-image: url({{catalogo.imgHero.url}})">
   <div class="priceHot">
        <i class="fas fa-dollar-sign"></i> <h3>{{catalogo.Sellprice}}</h3>
   </div>
</div>
    <div class="leerMas">
        <a href="" target="_blank">
        <i class="fas fa-search"></i>
    </a>
    </div>
  <div class="info">
      <h2>{{catalogo.title}}</h2>
      <p><i class="fas fa-map-marker-alt fa-pull-left"></i>{{catalogo.state}} </p>
      <p></p>
      
     {{catalogo.typeC}}
        
  </div>
  <div class="pie">
      <ul class="list-inline d-flex justify-content-around">
          <li class="list-inline-item">
              <a href="{{catalogo.googleS}}" target="_blank">
                <i class="fas fa-street-view"></i>
              </a>
          </li>
          <li class="list-inline-item">
                <a href="#" target="_blank">
                    <i class="fas fa-file-pdf"></i>
                </a>
            </li>
          <li class="list-inline-item">
              <a href="tel:{{catalogo.phone}}" target="_blank">
                <i class="fas fa-phone"></i>
              </a>
          </li> 
          <li class="list-inline-item">
                <a href="tel:{{catalogo.email}}" target="_blank">
                    <i class="fas fa-envelope"></i>
                </a>
            </li>
      </ul>
  </div> 
</div>
  
  {% endfor %} 
{% endblock %}